version: "3.1"
services:
  app:
    container_name: app
    image: app
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  proxy:
    container_name: proxy
    image: proxy
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app