version: "3.1"
services:
  app-server:
    container_name: app-server
    image: app-server
    build:
      context: app-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "6000:6000"
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx-proxy
    build:
      context: nginx-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app-server